# Generated by Django 3.2.4 on 2021-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Quantity'),
        ),
    ]
